dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hdorgeval-github"
    token:
      secure: "Z/JtUMrwiedVY7186Du9+ffsNpzd4XpX8gxqZIJgNcGz8oRhXWARS6/NV9po9MYd2exsNIABuBYaKcFP6KnTCATLXimgjKe2d0t+xsizACyLAI2YwA67ybMlRrC5hZ2+N2GgeXZVYwicm29NHjRJNPXDW6+dVIYCHU0kkRwvNYdylgbu5RzcbTf+5IRgmBSO2AP/ttbpFEbY82ywg8IesiF0qvctQWWNH+1GHqkpt+/m2y9f+m5Ww9nRnQBHewHmpVL03CdjHYds2ExwaMtK8IePRu4z6npoweoBQ3996ZSx+Wx2wM8Y1zBrLX+4tb9SusvdjhWDuG+vWxz1X4aGDxL0WYEld1QKU4CEovZrMWklPpXYoUpAhjEy4zno2kvxZet6lHY3iKe5TnfHxRfVfCWn6F1WLUi+Uz2oI9CT3GzW+52UTOHY00GQ6Hl6ZkVNAWSjeTR31MshkyDhTgvpNqF1vJYAgQYv7koWBYjj4HPkEKFi6Kmqo4w7hFbO66SVzmPn6xJT4DPvB5d4DoXSoppSRs/LAeYSd/l2KRmq8OizWYrUhlyrFLdYIUMKz/HyIKlMwEaEiYodoqguhIrzhML0/KN5GGZvm63h7O5jhbRjmbyT/WCh35fXJdPO5prGIPLL6uVMbzgdNJYvBMOJAwHuvZGhIPd8aKovT+trp8M="
    branches:
      - master
jdk:
  - oraclejdk8
language: node_js
cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
notifications:
  email: false
node_js:
  - '7'
  - '8'
before_install:
  - npm run update:cli
before_script:
  - npm prune
script:
  - npm run prettier:check
  - npm run lint
  - npm test
  - npm run build

after_success:
  - npm run codecov
  - npm run semantic-release
  - sonar-scanner -X -Dsonar.login=2876a76e8e830dc95d4ff7c5ae022f8a341c12ed

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
