language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '8'
before_install:
  - npm run update:cli
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - codecov
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
