dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "hdorgeval-github"
    token:
      secure: "Lcxf3fbujvv9IqMt/mcTVxP/tZZ0xN7OYZN7hMI+jLcCkodAHZEZ/3DYsbgmz3toW/E/FsQkyzckrVtWdX0uBcZz0AENqHrQjGw1YkJGMt+bb12UlgqJpPDLhc/7OfJBPj/5JTOnjRg6ZaayLI3nla9CSz5cNN4aAB7+kWAt93EgVxW5FAgSE7zJtJ0794zkyo4fMiHK14eW3vLhXQm24xJZsREcKCQzpSKLBpwJKj1nJGAAOhBgTtsL6CO6ges7c2GEdIYLDwf4W0IbRjBVk6EiQTV8D5G5kndY1jAwDqGvbcM1EpKEJZpnsIM7Tg+MGusQQxPda2wuyJH/yNQJMIymJ99N3T/c4behTnRAa+f3plBpz0Ix42l/EvBfHq8CJCYdQO+vyvGApb+Z7o8ZtiReTMiy6mo4eNLNfqiDxj2vbSv3FJPnEclGmHIUnPgV0KZOEq5QwxfKHt3U0sxF8fRnywdcl90cxu3budkM8zG+zAF/cuwnOdhj9Wa2i2vLediENBC2kgrLHLJUD5mK2rBVFlhazrFaCxH5gzqieXtTMQ52iFYQGyMsZGf7YBXb4XSZXx/gF6sxP04+A7arBqV7yNz7HVUy7ujiwMkgivYHDsEEOXulHqVp5tPBX/UwidxSnD2lTp3uSTYiyzMKUmgHFnODLj/cYFJFaRaMpuM="
    branches:
      - master
jdk:
  - oraclejdk8
language: node_js
cache:
  directories:
    - node_modules
    - '$HOME/.sonar/cache'
notifications:
  email: false
node_js:
  - '7'
  - '8'
before_install:
  - npm run update:cli
before_script:
  - npm prune
script:
  - npm run lint
  - npm test
  - npm run build

after_success:
  - codecov
  - npm run semantic-release
  - sonar-scanner

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
